# Generated by Django 5.2.6 on 2026-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('appliance', 'Home Appliance'), ('shirt', 'Shirt'), ('dress', 'Girls Dress')], default='mobile', max_length=20),
        ),
    ]
